[book]
authors = ["e-Yantra"]
language = "en"
multilingual = false
src = "src"
title = "e-Yantra Robotics Competition - ROS2 MOOC"

[build]
build-dir = "mooc_book"
create-missing = false

[output.html.fold]
enable = true
level = 0

[output.html.print]
enable = false

#[output.html.playground]
#editable = true
#copyable = true
#copy-js = true
#line-numbers = true

[output.html]
theme = "mooc_book_theme"
default-theme = "navy"
no-section-label = true
mathjax-support = true
additional-css = ["style.css"]
additional-js = ["sidebar.js"]
input-404 = "404.html"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[preprocessor.links]
[preprocessor.index]
